version: '3.9'

services:
  gateway:
    build: .
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/application.yml
    volumes:
      - ./application.yml:/config/application.yml:r
